---
- name: setup pre-requisites
  become: yes
  hosts: docker-nodes
  roles:
    - create-sudo-user
    - install-modules
    - configure-hosts-file

- name: setup docker user on the nodes
  become: yes
  become_user: mgmt
  hosts: admin
  roles:
    - configure-admin

- name: copy public key to nodes
  become: yes
  become_user: mgmt
  hosts: docker-nodes
  roles:
    - copy-keys

- name: install docker
  become: yes
  hosts: docker-nodes
  roles:
    - docker-installation

- name: initialize docker swarm
  become: yes
  hosts: swarm-manager
  roles:
    - docker-swarm-init

- name: add workers to the swarm
  become: yes
  hosts: swarm-workers
  roles:
    - docker-swarm-add-worker

