---
- name: Add Workers to the Swarm
  shell: "docker swarm join --token {{ hostvars['manager']['worker_token']['stdout'] }} {{ hostvars['manager']['ansible_default_ipv4']['address'] }}:2377"
  tags: swarm
